### ISSUE TITLE
Bug: main.py

### ISSUE THREAD

**Issue by xGreenNarae** [kakao-tech-campus-jnu-be1/bullsAndCows#14]
## Description

main.py 버그 수정

## Tasks

- [ ] random 숫자를 받아오는 함수 이름 random.py 의 generate_secret_number 로 변경 필요
- [ ] 게임시작 print 문에 큰따옴표 누락
- [ ] 숫자가 아닌 값으로 잘못입력시에도 attempt 가 증가하는 로직에 대한 고민 필요
- [ ] bull, cows 모두 do_cowscheck 함수를 통해 검사되고 있음
- [ ] bulls, cows 함수로 넘어가는 argument 순서 일치 필요
- [ ] 조건문 절의 들여쓰기 등이 잘못되어있음
