### ISSUE TITLE
Main 함수 구현

### ISSUE THREAD

**Issue by yuseonkim** [kakao-tech-campus-jnu-be1/bullsAndCows#5]
## Description
  게임 실행을 위한 메인함수
## Tasks

- [ ] Print "Bulls and Cows Start" 
- [ ] Repeat up to 10 times, or until the user correctly guesses all 4 digits (i.e., "Bulls" equals 4)
- [ ] Print "Game over" 
- [ ] import functions for game

## References

- [LinkText](LinkAddress)
